-- 입양 시각 구하기(2)
set @ROWNUM := -1;
SELECT A.HOUR,IFNULL(B.COUNT,0)AS 'COUNT'
FROM (SELECT @ROWNUM:=@ROWNUM+1 as HOUR FROM ANIMAL_OUTS) A
LEFT JOIN (SELECT HOUR(DATETIME) as HOUR,COUNT(*) as COUNT
FROM ANIMAL_OUTS GROUP BY HOUR(DATETIME) ) B
ON A.HOUR = B.HOUR WHERE A.HOUR<=23